### PR TITLE
adding testing framework

### PR DESCRIPTION
**Pull request by jimhavrilla**

### CODE REVIEW

**Review by kaichop — COMMENTED** [review]
what is "test_folders"? The contents (~200 files) are not int he commit so that I cannot reproduce the results. Please add them into the repo.

**Comment by jimhavrilla** [comment]
they're on respublica.  meant to be run on respublica.  we're not sure if
we can upload them legally right?

**Comment by kaichop** [comment]
what is the path to the folder?

**Comment by jimhavrilla** [comment]
It's in the script qsub.sh I thought

Jim

**Comment by jimhavrilla** [comment]
Yeah it's in there

**Pull request merged**
